'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SICAFI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _003() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("003", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _007() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("007", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _008() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("008", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _009() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("009", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _010() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("010", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _025() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("025", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _028() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("028", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _041() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("041", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _045() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("045", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _047() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("047", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _060() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("060", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _064() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("064", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _073() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("073", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _074() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("074", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _084() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("084", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0841() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0841", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _096() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("096", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _105() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("105", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1065() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1065", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1100() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1100", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1104() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1104", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _11041() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("11041", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _113() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("113", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _117() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("117", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1172() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1172", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _118() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("118", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _119() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("119", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _120() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("120", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _125() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("125", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1295() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1295", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _132() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("132", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _133() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("133", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _136() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("136", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _137() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("137", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _142() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("142", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _147() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("147", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _147_a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("147-a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1471() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1471", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _151() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("151", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _155() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("155", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _156() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("156", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1611() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1611", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _167() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("167", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1671() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1671", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _171() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("171", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _173() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("173", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _174() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("174", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _179() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("179", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _187() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("187", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _198() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("198", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _208() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("208", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _210() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("210", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _212() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("212", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _221() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("221", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _222() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("222", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _227() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("227", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _229() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("229", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _230() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("230", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _243() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("243", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _2431() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2431", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _249() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("249", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _295() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("295", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _312() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("312", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _387() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("387", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _412() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("412", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _42() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("42", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _45() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("45", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _499() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("499", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _505() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("505", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _507() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("507", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _526() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("526", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _548() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("548", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _585() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("585", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _615() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("615", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _645() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("645", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _667() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("667", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _677() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("677", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _71() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("71", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _722() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("722", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _73() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("73", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _787() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("787", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _81() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("81", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _834() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("834", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _934() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("934", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Configure() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("!Configure", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Error() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Error", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property access() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("access", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property base() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("base", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bienes3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bienes3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bienes4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bienes4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bienes7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bienes7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DEFINICIONES Y OBJETIVOS
        '''
        '''
        '''ARTÍCULO 1°.  Definición de Catastro.  El Catastro es el inventario o censo, debidamente actualizado y clasificado, de los bienes inmuebles pertenecientes al
        '''Estado y a los particulares, con el objeto de lograr su correcta identificación física,
        '''jurídica, fiscal y económica.
        '''.
        '''</summary>
        Friend ReadOnly Property Catastro() As String
            Get
                Return ResourceManager.GetString("Catastro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property concepto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("concepto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Contenido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Contenido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cuentas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuentas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cuentas1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cuentas1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dibujo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dibujo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dibujo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dibujo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dibujo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dibujo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PAUTAS  PARA EL DILIGENCIAMIENTO DE LA NUEVA FICHA PREDIAL
        '''
        '''Para el diligenciamiento de la ficha predial  tener en cuenta las siguientes normas generales:
        ''' 
        '''-Letra legible
        '''-Letra imprenta mayúscula excepto las abreviaturas  y complementos de la dirección.
        '''-Tinta negra 
        '''-No se permite el uso de tinta mojada, ni borrable
        '''-Utilizar lápiz color rojo para identificar mejoras
        '''-Resaltador verde para cambio en la información 
        '''-Utilizar lápiz negro MIRADO nro. 2 o en su defecto minas HB para realizar el cr [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Diligenciamiento_de_la_ficha_predial() As String
            Get
                Return ResourceManager.GetString("Diligenciamiento_de_la_ficha_predial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DRIVE02A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRIVE02A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DRIVE02A1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRIVE02A1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property edicion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("edicion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IMPORTACION OBSERVACION FICHA PREDIAL
        '''
        '''CAMPOS:
        '''NUMERO DE FICHA (NUMERICO)
        '''OBSERVACION     (ALFANUMERICO 1000)
        '''.
        '''</summary>
        Friend ReadOnly Property Estrcutura_importacion_observacion_ficha_predial() As String
            Get
                Return ResourceManager.GetString("Estrcutura_importacion_observacion_ficha_predial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA EL CRUCE DE AREAS DE TERRENO BD VS CARTOGRAFIA
        '''
        '''CAMPOS:
        '''
        '''MUNICIPIO  (NUMERICO)
        '''CORREGIMIENTO  (NUMERICO)
        '''BARRIO  (NUMERICO)
        '''MANZANA  (NUMERICO)
        '''PREDIO (NUMERICO)
        '''SECTOR  (NUMERICO)
        '''AREA DE TERRENO (NUMERICO)
        '''
        '''NOTA: EL LISTADO DE INFORMACION DEBE CONTENER EL NOMBRE DE LAS COLUMNAS. .
        '''</summary>
        Friend ReadOnly Property Estructura_cruce_areas_bd_vs_cartografia() As String
            Get
                Return ResourceManager.GetString("Estructura_cruce_areas_bd_vs_cartografia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA CRUCE MATRICULAS MUNICIPIO VS REGISTRO XLS - MDB 
        '''
        '''CAMPO 1: MATRICULA
        '''CAMPO 2: SECTOR
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property ESTRUCTURA_CRUCE_MATRICULAS_MUNICIPIO_VS_REGISTRO_XLS___MDB() As String
            Get
                Return ResourceManager.GetString("ESTRUCTURA_CRUCE_MATRICULAS_MUNICIPIO_VS_REGISTRO_XLS___MDB", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA IMPORTAR RESOLUCIONES ADMINISTRATIVAS
        '''
        '''CAMPOS:
        '''
        '''TIPO DE RESOLUCION (NUMERICO)
        '''NRO DE FICHA       (NUMERICO)
        '''NRO DE RESOLUCION  (NUMERICO)
        '''CLASE O SECTOR     (NUMERICO)
        '''VIGENCIA           (NUMERICO)
        '''AREA DE TERRENO    (NUMERICO)
        '''OBSERVACION        (CARACTER 100)
        '''ESTADO             (CARACTER 2).
        '''</summary>
        Friend ReadOnly Property Estructura_de_importacion_resoluciones_administrativas() As String
            Get
                Return ResourceManager.GetString("Estructura_de_importacion_resoluciones_administrativas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estructura de importación zona económica ficha predial
        '''
        '''Campos:
        '''-	Nro. Ficha Predial = Numérico
        '''-	Zona = Numérico
        '''-	Porcentaje = Numérico
        '''.
        '''</summary>
        Friend ReadOnly Property Estructura_de_importacion_zona_economica_ficha_predial() As String
            Get
                Return ResourceManager.GetString("Estructura_de_importacion_zona_economica_ficha_predial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA ICARE
        '''
        '''CAMPOS:
        '''MATRICULA	-	CARÁCTER
        '''PREDIAL 	-	CARÁCTER
        '''TIPO		-	CARÁCTER
        '''DIRECCION	-	CARÁCTER
        '''PROPIETARIO	-	CARÁCTER	
        '''ESTADO      	-	CARÁCTER
        '''.
        '''</summary>
        Friend ReadOnly Property Estructura_ICARE() As String
            Get
                Return ResourceManager.GetString("Estructura_ICARE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA IMPORTAR LA INVESTIGACIÓN JURIDICA
        '''
        '''LAS COLUMNAS DEBEN CONTENER UN NOMBRE DEL CAMPO EN LA PRIMERA FILA EN EL SIGUIENTE ORDEN:
        '''
        '''NUMERO DE FICHA           - NUMERICO
        '''FOLIO                     - ALFANUMERICO(100)
        '''MATRICULA SEGREGADA       - ALFANUMERICO(100)
        '''MATRICULA ABIERTA         - ALFANUMERICO(100)
        '''TOMO ABIERTO              - ALFANUMERICO(100)
        '''FOLIO ABIERTO             - ALFANUMERICO(100)
        '''AREA DE TERRENO           - ALFANUMERICO(100)
        '''FALSA TRADICIÓN           - BOLEANO(VERDADERO [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Estructura_Importacion_Investigacion_Juridica() As String
            Get
                Return ResourceManager.GetString("Estructura_Importacion_Investigacion_Juridica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA IMPORTAR EL REGISTRO Y CONTROL DE FICHA PREDIAL Y RESUMEN
        '''
        '''LAS COLUMNAS DEBEN CONTENER UN NOMBRE DEL CAMPO EN LA PRIMERA FILA EN EL SIGUIENTE ORDEN:
        '''
        '''NUMERO DE FICHA           - NUMERICO
        '''INGENIERO                 - ALFANUMERICO(100)
        '''PREDIADOR                 - ALFANUMERICO(100)
        '''EMPRESA                   - ALFANUMERICO(100)
        '''PROPIETARIO               - ALFANUMERICO(100)
        '''REPRESENTANTE             - ALFANUMERICO(100)
        '''FECHA                     - ALFANUMERICO(10) (dd-mm-aaaa)
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property Estructura_Importacion_Registro_y_Control() As String
            Get
                Return ResourceManager.GetString("Estructura_Importacion_Registro_y_Control", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA IMPORTAR LA CEDULA CATASTRAL
        '''
        '''ESTRUCTURA PARA CAMBIOS DE CEDULA DENTRO DE UN MISMO SECTOR
        '''CAMPOS:
        '''
        '''NUMERO_FICHA (NUMERICO)
        '''MUNICIPIO_ACTUAL  (NUMERICO)
        '''CORREGIMIENTO_ACTUAL  (NUMERICO)
        '''BARRIO_ACTUAL  (NUMERICO)
        '''MANZANA_ACTUAL  (NUMERICO)
        '''PREDIO_ACTUAL (NUMERICO)
        '''EDIFICIO_ACTUAL (NUMERICO)
        '''UNIDAD_ACTUAL (NUMERICO)
        '''SECTOR_ACTUAL  (NUMERICO)
        '''MUNICIPIO_NUEVO  (NUMERICO)
        '''CORREGIMIENTO_NUEVO  (NUMERICO)
        '''BARRIO_NUEVO  (NUMERICO)
        '''MANZANA_NUEVO  (NUMERICO)
        '''PREDIO_NUEVO (NUMERICO)
        '''E [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Estructura_importar_cedula_catastral() As String
            Get
                Return ResourceManager.GetString("Estructura_importar_cedula_catastral", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA DE IMPORTACIÓN DE HISTORICOS DE AVALÚOS
        '''CAMPOS:
        '''-	VIGENCIA
        '''-	NRO. DE FICHA
        '''-	AREA TERRENO PRIVADA
        '''-	AREA TERRENO COMUN
        '''-	AREA CONSTRUCCIÓN PRIVADA
        '''-	AREA CONSTRUCCIÓN COMUN
        '''-	VALOR TERRENO PRIVADO
        '''-	VALOR TERRENO COMUN
        '''-	VALOR CONSTRUCCIÓN PRIVADA
        '''-	VALOR CONSTRUCCIÓN COMUN
        '''-	AVALUO TOTAL
        '''.
        '''</summary>
        Friend ReadOnly Property Estructura_importar_historicos_de_avaluo() As String
            Get
                Return ResourceManager.GetString("Estructura_importar_historicos_de_avaluo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA GENERAR AREAS DE CONSTRUCCIÓN MEDIANTE POLIGONOS
        '''
        '''CAMPOS:
        '''
        '''PK_CONSTRUCCIONES = ALFANUMERICO(33)
        '''TIPO = ALFANUMERICO
        '''USO = ALFANUMERICO
        '''SHAPE_AREA = DECIMAL
        '''.
        '''</summary>
        Friend ReadOnly Property Estructura_para_generar_areas_de_construcción_mediante_poligonos() As String
            Get
                Return ResourceManager.GetString("Estructura_para_generar_areas_de_construcción_mediante_poligonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA CARGAR LAS AREAS DE TERRENO
        '''
        '''CAMPOS:
        '''MUNICIPIO (3) - CARACTER
        '''CORREGIMIENTO (2) - CARACTER
        '''BARRIO (3) - CARACTER
        '''MANZANA (3) - CARACTER
        '''PREDIO (5) - CARACTER
        '''SECTOR (1) - NUMERICO
        '''AREAS TERRENO (22) - NUMERICO
        '''
        '''NOTA: los campos alfanumericos debe tener la marcara de la misma longitud del campo indicado.
        '''</summary>
        Friend ReadOnly Property Estructura_para_importar_area_de_terreno() As String
            Get
                Return ResourceManager.GetString("Estructura_para_importar_area_de_terreno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA UTILIZADA PARA IMPORTAR LOS DATOS DEL PROPIETARIO ANTERIOR
        '''
        '''Se debe crear un archivo en excel versión 2003 conformada por los siguientes campos:
        '''
        '''1. Numero de ficha
        '''2. Numero de documento del propietario actual
        '''3. Primer apellido
        '''4. Segundo apellido
        '''5. Nombre
        '''6. Causa del acto
        '''
        '''Nota: Se debe crear cada columna con su correspondiente titulo ubicada en la primera fila.
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property Estructura_para_importar_el_propietario_anterior() As String
            Get
                Return ResourceManager.GetString("Estructura_para_importar_el_propietario_anterior", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA CARGAR LAS AREAS DE CONSTRUCCION
        '''
        '''CAMPOS:
        '''MUNICIPIO (3) - CARACTER
        '''CORREGIMIENTO (2) - CARACTER
        '''BARRIO (3) - CARACTER
        '''MANZANA (3) - CARACTER
        '''PREDIO (5) - CARACTER
        '''EDIFICIO (3) - CARACTER
        '''UNIDAD (5) - CARACTER
        '''SECTOR - NUMERICO
        '''NRO CONSTRUCCION - NUMERICO
        '''AREA CONSTRUCCION - DECIMAL
        '''
        '''NOTA: los campos alfanumericos debe tener la marcara de la misma longitud del campo indicado.
        '''</summary>
        Friend ReadOnly Property EstructuraImportacionAreaDeConstruccion() As String
            Get
                Return ResourceManager.GetString("EstructuraImportacionAreaDeConstruccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estructura importación categoría de predio ficha predial
        '''
        '''-	Numero ficha predial (numérico)
        '''-	Categoría de predio (numérico)
        '''.
        '''</summary>
        Friend ReadOnly Property EstructuraImportacionCategoriaPredio() As String
            Get
                Return ResourceManager.GetString("EstructuraImportacionCategoriaPredio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA IMPORTACIÓN COEFICIENTE DE EDIFICIO
        '''
        '''CAMPOS:
        '''NUMERO DE FICHA - NUMERICO
        '''COEFICIENTE DE EDIFICIO - DECIMAL
        '''
        '''NOTA:
        '''LOS DECIMALES DEL COEFICIENTE DE EDIFICIO SERAN SEPARADOS POR EL SIGNO PUNTO.
        '''.
        '''</summary>
        Friend ReadOnly Property EstructuraImportacionCoeficienteDeEdificio() As String
            Get
                Return ResourceManager.GetString("EstructuraImportacionCoeficienteDeEdificio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA DE INFORMACION DE RPH
        '''
        '''CAMPOS:
        '''-	NRO DE FICHA  (NUMERICO)
        '''-	DIRECCION (CARACTER)
        '''-	MATRICULA (NUMERICO)
        '''-	AREA CONSTRUCCION (DECIMAL)
        '''-	COEFICIENTE EDIFICIO (DECIMAL)
        '''.
        '''</summary>
        Friend ReadOnly Property EstructuraImportacionInformacionRPH() As String
            Get
                Return ResourceManager.GetString("EstructuraImportacionInformacionRPH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA CARGAR EL NUMERO DE LA FICHA
        '''
        '''CAMPOS:
        '''NRO DE FICHA ACTUAL - NUMERICO
        '''NRO DE FICHA NUEVA - NUMERICO
        '''
        '''
        '''NOTA: los campos alfanumericos debe tener la marcara de la misma longitud del campo indicado.
        '''</summary>
        Friend ReadOnly Property EstructuraImportacionNumeroDeFicha() As String
            Get
                Return ResourceManager.GetString("EstructuraImportacionNumeroDeFicha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA IMPORTAR IDENTIFICADOR DE CONSTRUCCIÓN
        '''
        '''TABLA
        '''
        '''DEPARTAMENTO          ALFANUMERICO(2)
        '''MUNICIPIO             ALFANUMERICO(3)
        '''CLASE O SECTOR        NUMERICO
        '''CLASE DE CONSTRUCCIÓN NUMERICO
        '''TIPO DE CALIFICACIÓN  ALFANUMERICO(1)
        '''IDENTIFICADOR         ALFANUMERICO(3)
        '''DESCRIPCIÓN           ALFANUMERICO(50)
        '''PUNTAJE PREDETERM.    NUMERICO
        '''PUNTAJE MAXIMO        NUMERICO
        '''ESTADO                ALFANUMERICO(2)
        '''.
        '''</summary>
        Friend ReadOnly Property Estructurta_importar_identificador_de_construccion() As String
            Get
                Return ResourceManager.GetString("Estructurta_importar_identificador_de_construccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA DE IMPORTACIÓN DE LINDEROS DE FICHA PREDIAL
        '''
        '''CAMPOS:
        '''-	NRO DE FICHA (NUMERICO)
        '''-	PUNTO CARDINAL NORTE (ALFANUMERICO)
        '''-	PUNTO CARDINAL NORTE (ALFANUMERICO)
        '''-	PUNTO CARDINAL NORTE (ALFANUMERICO)
        '''-	PUNTO CARDINAL NORTE (ALFANUMERICO)
        '''-	PUNTO CARDINAL ORIENTE (ALFANUMERICO)
        '''-	PUNTO CARDINAL ORIENTE (ALFANUMERICO)
        '''-	PUNTO CARDINAL ORIENTE (ALFANUMERICO)
        '''-	PUNTO CARDINAL ORIENTE (ALFANUMERICO)
        '''-	PUNTO CARDINAL SUR (ALFANUMERICO)
        '''-	PUNTO CARDINAL SUR (ALFANUMERICO)
        '''-	PUNTO CARDINAL SUR (AL [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExtructuraImportacionLinderosFichaPredial() As String
            Get
                Return ResourceManager.GetString("ExtructuraImportacionLinderosFichaPredial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a AVALÚOS CATASTRALES DEL MUNICIPIO DE ENVIGADO
        '''
        '''
        '''CARACTERÍSTICA 1 NORMAL
        '''
        '''
        '''Áreas de Terreno Ficha predial   
        '''
        '''Ø	Área de terreno x valor de la zona x % c/u zonas x % descuento. (área de terreno privada - valor lote privado).
        '''
        '''Área de Construcción Ficha predial  
        '''
        '''Ø	Área de construcción x valor de los puntos que tiene el tipo de construcción. (área construida privada - valor construcción privada).
        '''
        '''
        '''CARACTERÍSTICA 2 RPH EDIFICIO
        '''
        '''
        '''Áreas de Terreno Ficha resumen 2
        '''
        '''Ø	Área común de lote FR2 x [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Formulas_de_liquidación_de_avalúos_catastrales() As String
            Get
                Return ResourceManager.GetString("Formulas_de_liquidación_de_avalúos_catastrales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frm_ok() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frm_ok", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property frm_ok1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frm_ok1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESTRUCTURA PARA GENERAR AREAS DE CONSTRUCCIÓN MEDIANTE POLIGONOS
        '''
        '''CAMPOS:
        '''
        '''PK_CONSTRUCCIONES = ALFANUMERICO(33)
        '''TIPO = ALFANUMERICO
        '''USO = ALFANUMERICO
        '''NRO_PISOS = NUMEICO
        '''SHAPE_AREA = DECIMAL.
        '''</summary>
        Friend ReadOnly Property Generar_areas_mediante_poligonos() As String
            Get
                Return ResourceManager.GetString("Generar_areas_mediante_poligonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property graph07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graph07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grupo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grupo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HARDRV1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HARDRV1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingrese la lista de valores o active los registros de las tablas de mantenimiento que corresponden al código padre que se ubican en las listas desplegables del formulario modificar registro..
        '''</summary>
        Friend ReadOnly Property INCO_eliminar_registro() As String
            Get
                Return ResourceManager.GetString("INCO_eliminar_registro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingrese la lista de valores o active los registros de las tablas de mantenimiento que corresponden al código padre que se ubican en las listas desplegables del formulario insertar registro..
        '''</summary>
        Friend ReadOnly Property INCO_insertar_registro() As String
            Get
                Return ResourceManager.GetString("INCO_insertar_registro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingrese la lista de valores o active los registros de las tablas de mantenimiento que corresponden al código padre que se ubican en las listas desplegables del formulario modificar registro..
        '''</summary>
        Friend ReadOnly Property INCO_modificar_registro() As String
            Get
                Return ResourceManager.GetString("INCO_modificar_registro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Key06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Key06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LEY 14 DE 1983
        '''(Julio 6)
        '''EL CONGRESO DE COLOMBIA
        '''DECRETA:
        '''CAPÍTULO I
        '''NORMAS SOBRE CATASTRO, IMPUESTO PREDIAL
        '''E IMPUESTO DE RENTA Y COMPLEMENTARIOS 
        ''' 
        '''
        '''ARTÍCULO 1o.  El avalúo catastral de todos los inmuebles se actualizará durante el año de 1983.  Para este efecto el último avalúo vigente se reajustará en un diez por ciento (10%) anual acumulado, año por año, de acuerdo con su antigüedad o fecha.  El período del reajuste no podrá exceder de 15 años. 
        '''El Instituto Geográfico &quot;Agustín Codazzi&quot; y las [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ley_14_de_1983() As String
            Get
                Return ResourceManager.GetString("Ley_14_de_1983", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONGRESO DE LA REPÚBLICA
        '''LEY 675 DE 2001
        '''(agosto 3)
        ''' 
        '''Diario Oficial No. 44.509, de 4 de agosto de 2001
        ''' 
        '''Por medio de la cual se expide el régimen de propiedad horizontal.
        ''' 
        '''Vigencia. Esta disposición fue modificada por el Decreto 1380 de 2002.
        ''' 
        '''La Corte Constitucional en sentencia C-782/04 declaró la exequibilidad, pero únicamente por los cargos analizados, del artículo 25 numeral 3 de la Ley 675 de 2001, así como el aparte acusado del artículo 3 de esa misma Ley, el cual literalmente dice: &quot;la [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ley_675_de_2001() As String
            Get
                Return ResourceManager.GetString("Ley_675_de_2001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MYCOMP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MYCOMP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property novedad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novedad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PROCEDIMIENTO PARA INFORMAR LOS MOVIMIENTOS
        '''
        '''APLICATIVO PARA LA CAPTURA DE INFORMACIÓN CATASTRAL
        '''
        '''
        '''Al llamar el PROGRAMA se debe LLENAR la siguiente información para INGRESAR:
        '''
        '''Usuario: Ingrese el usuario de la persona que usará el aplicativo. Debe ser una palabra con máximo 18  caracteres. Por defecto, el usuario general será ADMIN
        '''
        '''Clave: Ingrese la clave de acceso al aplicativo asignada al usuario. Por seguridad, esta no se visualiza en el campo. Debe ser una palabra con máximo 18 caracteres.
        '''        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Procedimientos_para_informar_movimientos() As String
            Get
                Return ResourceManager.GetString("Procedimientos_para_informar_movimientos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property procesos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("procesos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Raiz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Raiz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RECONOCIMIENTO Y CALIFICACIÓN DE LAS CONSTRUCCIONES
        '''
        '''
        '''
        '''
        '''Variables
        '''
        '''
        '''Para efectos del reconocimiento, clasificación y calificación de los diversos tipos de edificaciones existentes teniendo como objetivo final el avalúo catastral, se han escogido cuatro variables, consideradas como las más representativas dentro de la inmensa gama de características posibles de reconocer en las construcciones y las que mejor explican el avalúo de la construcción.  Algunas de ellas de carácter censal sobre condiciones [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Reconocimiento_y_calificación_de_las_construcciones() As String
            Get
                Return ResourceManager.GetString("Reconocimiento_y_calificación_de_las_construcciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Reconsultar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reconsultar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property recuhuma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("recuhuma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''												
        '''
        '''
        '''RESOLUCIÓN No 2555 DE 1988
        '''(28 SEP. 1988)
        '''
        '''
        '''Por la cual se reglamenta la formación, actualización de la formación y conservación del Catastro Nacional, y subroga la resolución No. 660 de 30 de 
        '''marzo de 1984.
        '''
        '''
        '''EL DIRECTOR GENERAL DEL INSTITUTO GEOGRÁFICO 
        '''&quot; AGUSTÍN CODAZZI&quot;
        '''
        '''
        '''En uso de sus atribuciones legales y en especial las que le confieren la Ley 65 de 
        '''1939, el Decreto 1301 de 1940, el Decreto Ley 290 de 1957, el Decreto 2205 de 1983, la Ley 14 de 1983 y el Decreto 34 [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Resolución_2555_de_1998() As String
            Get
                Return ResourceManager.GetString("Resolución_2555_de_1998", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSTITUTO GEOGRÁFICO AGUSTÍN CODAZZI
        '''
        '''RESOLUCIÓN Nº 0070 DE 2011
        '''
        '''(Febrero 4)
        '''
        '''&quot;Por la cual se reglamenta técnicamente la formación catastral, la actualización de la formación catastral y la conservación catastral&quot;.
        '''
        '''El Director General del Instituto Geográfico Agustín Codazzi, en uso de sus atribuciones legales, y en especial las que le confieren la Ley 65 de 1939, el Decreto 1301 de 1940, la Ley 14 de 1983, el Decreto 3496 de 1983, el Decreto 2113 de 1992 y el Decreto 208 de 2004, y
        '''
        '''
        '''CONSIDERA [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend ReadOnly Property Resolucion_N_70_de_2011() As String
            Get
                Return ResourceManager.GetString("Resolucion_N_70_de_2011", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property seven() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("seven", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property usuario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usuario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Validacion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Validacion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Word() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Word", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
